columns_to_use: [['ORGANIZATION_TYPE', 'EXT_SOURCE_3', 'DAYS_TO_END_B', 'EXT_SOURCE_1', 
                  'DPD_INSTALLMENTS', 'EXT_SOURCE_2', 'DAYS_BIRTH', 'DAYS_SINCE_ENDED_B', 
                  'DAYS_ID_PUBLISH', 'AVG_AMOUNT_ANNUITY_PA', 'ACCEPTED_CREDICT_PA', 'DAYS_REGISTRATION', 
                  'SK_PREV_POS', 'AMT_ANNUITY', 'DAYS_LAST_PHONE_CHANGE', 'AMT_CREDIT', 
                  'FRAC_PAID_INSTALLMENTS', 'DAYS_EMPLOYED', 'PREV_CRED_INSTALLMENTS', 'MAX_AMT_CREDIT_PA']]