columns_to_use_1: [ 'SK_ID_CURR','TARGET',
                  'ORGANIZATION_TYPE',
                  'EXT_SOURCE_3',
                  'DAYS_TO_END_B',
                  'EXT_SOURCE_2',
                  'EXT_SOURCE_1',
                  'DAYS_SINCE_ENDED_B',
                  'DPD_INSTALLMENTS',
                  'AMT_GOODS_PRICE',
                  'ACCEPTED_CREDICT_PA',
                  'DAYS_BIRTH',
                  'DAYS_ID_PUBLISH',
                  'DAYS_REGISTRATION',
                  'AVG_AMOUNT_ANNUITY_PA',
                  'FRAC_PAID_INSTALLMENTS',
                  'DAYS_EMPLOYED',
                  'SK_PREV_POS',
                  'DAYS_LAST_PHONE_CHANGE',
                  'PREV_CRED_INSTALLMENTS',
                  'MAX_AMT_CREDIT_PA',
                  'CREDIT_TYPE_COUNT_B',
                  'AMT_ANNUITY',
                  'AMT_CREDIT']

columns_to_use_2: ['SK_ID_CURR','TARGET',
                 'ORGANIZATION_TYPE',
                 'EXT_SOURCE_1',
                 'EXT_SOURCE_3',
                 'EXT_SOURCE_2',
                 'CC_LIMIT_USAGE',
                 'FRAC_PAID_INSTALLMENTS',
                 'AMT_CREDIT',
                 'ACCEPTED_CREDICT_PA',
                 'AMT_ANNUITY',
                 'SK_PREV_POS',
                 'AMT_GOODS_PRICE',
                 'AVG_AMOUNT_ANNUITY_PA',
                 'DAYS_BIRTH',
                 'FUTURE_INSTALLMENTS_POS',
                 'OWN_CAR_AGE',
                 'DAYS_TO_END_B',
                 'DAYS_EMPLOYED',
                 'OCCUPATION_TYPE',
                 'DPD_INSTALLMENTS',
                 'CODE_GENDER']